sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: ZSGTK+Ktzx6coG8nIk6kOA+xmbQBfNn390D0BgvJW0ggQtXYPDVzLKFu6evwkEPevAnC/TeYByMgOWfw4javIF0uWtiK33u4qohTp91U2Gha984jp2uHmA6/XzEVMCNm0maqp3PGjwtU+ydDcV2dMQK4zQAkL/zclNVvA/N2yxXoOlgfYuVHMgu7bMuXp+VWrmQujixtj2FYFpn4goQHkECQzhUInYAkE9O1ezDWmNUPpHTOqNckIeuMod5fL3D5g5Yk7Ra9tcIF4NFIp4bA8/Yc39CY5VCY6ETBu/Xd4YGEBChqi99Ma9cYqSgoj5I/G6Q3McruE5eT9quFJojE4+c3VUjs/HXakUGqG+qbCr6oAKbTqFxRPzisDIQedZ2p/wg41CzpxqSVr3RtQBpPImASFzLPC0g6Fu0eP1Y+JhyXV8AOfrqPZx7lPff3TH8dTuXicvfO9pWEpGLm+ZjT9cMiJ+c5U2X5bXD2xKcBM2OtIXsEiHb6H90hzQfHqhG3UFE35t1NU0TqmXFATHNST3qdAX/U42bkfAvjLGh3v9D/0CwYk2YR91lJxxkUFpWWpctSfd2hQarXNb0kFZP9BOzE71ZaIEVd+z+ntGON3iRuLUOqaZmclzWzBm7/03GTrkIeScOkRoI1WfKij3RKJBhY7jdJOTEQA/uoCIgARTQ=
  - secure: ZnZlh1HZjMtjWkRrp/W3PbEtdZpRHZejby2L5/9jlJqdYGz6JUHG6R01a/Qp29zQHm0MliYdgiHw81S/o9KS7FesQ5x9KpCY6KUQNSRh6CcAIv8aXqgQQuzjShXJyy7B+wMrtObDESHl5PvWpwRZeGcEjH7Kl3das5nOzV0dDKIh5JHwbweYObRW/EByBIqf6cWdlbKT0Jq4YzAEQGKHrSSVC4wGfW6Jv/XsvvDDjqEC8ZsyCztqIK93F7TtU0GqCTh1H12uFYF0gryY0HTesTTy8rICviFdY219njJaGpEjcndSEMYM4fowptC72b57D76CdmtRoCR20HsOLy7PSEI+V8PwfsxcWoBDTUzNoorVqShJL2BWGAPsOH+llMtf3Hos0eVpb9+kw9szLsvRv5peKittVLNajkNuxEoqj6u3mHvyE0h22v5/VN9R67XShyjp7ffLusVQRajkuwjjwJ14bNSmEpil5K6Y7R9oL84kRZkHuSX5jUJLsR/mbo80Pub05jVMbLYSBIignGhGjkqu6l3+V1VvnhZVgdmj995T/Wuhtux5cHy8TSABggYZ+o3h83QECzAfz64f3NKdFFSeZYGE3A/p1nFrGe2p4C31h3QlWSuE5wwVYnt3+JACUiCnASmZLJ94gb6Gk4Wo4FSuJ9W4gk8ZU2mIXZUGSqo=
